import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import ayanPic from '../../images/myProfilePicture.jpeg';
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Aryan",
    lastName: "More",
    username: "aryanmore2110",
    image: `${ayanPic}`,
    password: "aryanmore",
    bookmarks: [],
    bio: "Frontend Developer",
    portfolio: "https://portfolioaryan.netlify.app/",
    followers: [
      {
        _id: "007",
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        image: 'jane'
      },
      {
        _id: uuid(),
        firstName: "John",
        lastName: "Doe",
        username: "johndoe",
        image: "john",
      },
    ],
    following: [
      {
        _id: "007",
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        image: "jane",
      },
      {
        _id: uuid(),
        firstName: "John",
        lastName: "Doe",
        username: "johndoe",
        image: "john",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "John",
    lastName: "Doe",
    username: "johndoe",
    password: "password123",
    image: "https://example.com/profile_images/johndoe.jpg",
    bookmarks: [],
    bio: "Hello, I'm John Doe!",
    portfolio: "https://example.com/portfolio/johndoe",
    followers: [],
    following: [],
    createdAt: "2023-07-04T10:30:00Z",
    updatedAt: "2023-07-04T10:30:00Z",
  },
  {
    _id: "007",
    firstName: "Jane",
    lastName: "Smith",
    username: "janesmith",
    password: "pass123",
    image: "https://example.com/profile_images/janesmith.jpg",
    bookmarks: [],
    bio: "Hey there, I'm Jane Smith!",
    portfolio: "https://example.com/portfolio/janesmith",
    followers: [],
    following: [],
    createdAt: "2023-07-04T09:45:00Z",
    updatedAt: "2023-07-04T09:45:00Z",
  },
  {
    _id: uuid(),
    firstName: "Alice",
    lastName: "Johnson",
    username: "alicejohnson",
    password: "abcde",
    image: "https://example.com/profile_images/alicejohnson.jpg",
    bookmarks: [],
    bio: "Hi, I'm Alice Johnson!",
    portfolio: "https://example.com/portfolio/alicejohnson",
    followers: [
      {
        _id: "007",
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        image: 'jane'
      },
      {
        _id: uuid(),
        firstName: "John",
        lastName: "Doe",
        username: "johndoe",
        image: "john",
      },
    ],
    following: [
      {
        _id: "007",
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        image: 'jane'
      },
      {
        _id: uuid(),
        firstName: "John",
        lastName: "Doe",
        username: "johndoe",
        image: "john",
      },
    ],
    createdAt: "2023-07-04T08:15:00Z",
    updatedAt: "2023-07-04T08:15:00Z",
  },
  {
    _id: "a1b2c3d4-5678-90ab-cdef-0123456789ab",
    firstName: "Michael",
    lastName: "Brown",
    username: "michaelbrown",
    password: "password456",
    image: "https://example.com/profile_images/michaelbrown.jpg",
    bookmarks: [],
    bio: "Hello, I'm Michael Brown!",
    portfolio: "https://example.com/portfolio/michaelbrown",
    followers: [],
    following: [],
    createdAt: "2023-07-04T12:00:00Z",
    updatedAt: "2023-07-04T12:00:00Z",
  },
  {
    _id: "b2a1c3d4-5678-90ab-cdef-0123456789ab",
    firstName: "Emily",
    lastName: "Wilson",
    username: "emilywilson",
    password: "qwerty",
    image: "https://example.com/profile_images/emilywilson.jpg",
    bookmarks: [],
    bio: "Hi there, I'm Emily Wilson!",
    portfolio: "https://example.com/portfolio/emilywilson",
    followers: [],
    following: [],
    createdAt: "2023-07-04T11:30:00Z",
    updatedAt: "2023-07-04T11:30:00Z",
  },
  {
    _id: "c3d4a1b2-5678-90ab-cdef-0123456789ab",
    firstName: "David",
    lastName: "Taylor",
    username: "davidtaylor",
    password: "password789",
    image: "https://example.com/profile_images/davidtaylor.jpg",
    bookmarks: [],
    bio: "Hey, I'm David Taylor!",
    portfolio: "https://example.com/portfolio/davidtaylor",
    followers: [],
    following: [],
    createdAt: "2023-07-04T11:00:00Z",
    updatedAt: "2023-07-04T11:00:00Z",
  }
];